services:
  hive-metastore-db:
    container_name: hive-metastore-db
    hostname: hive-metastore-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${HIVE_METASTORE_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${HIVE_METASTORE_DB_NAME}
      MYSQL_USER: ${HIVE_METASTORE_DB_USER}
      MYSQL_PASSWORD: ${HIVE_METASTORE_DB_PASSWORD}
    volumes:
      - hive-metastore-db-data:/var/lib/mysql
    networks:
      internal:
        ipv4_address: ${HIVE_METASTORE_DB_IP}
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      retries: 5
      timeout: 5s

  hive-server:
    container_name: hive-server
    hostname: hive-server
    build:
      context: ${PWD}/hive
      dockerfile: Dockerfile
      args:
        - HIVE_VERSION=${HIVE_VERSION}
        - HADOOP_VERSION=${HADOOP_VERSION}
    depends_on:
      hive-metastore-db:
        condition: service_healthy
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HIVE_HOME=/opt/hive
    volumes:
      - ${PWD}/secrets/gcp-sa.json:/opt/gcp/secrets/service-account.json
      - ${PWD}/hive/hive-site.xml:/opt/hive/conf/hive-site.xml
      - ${PWD}/hive/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
    networks:
      internal:
        ipv4_address: ${HIVE_SERVER_IP}
    healthcheck:
      test: ['CMD-SHELL', 'nc -zv localhost 9083 || exit 1']
      interval: 10s
      retries: 5
      timeout: 5s

  trino-event-db:
    container_name: trino-event-db
    hostname: trino-event-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${TRINO_EVENT_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TRINO_EVENT_DB_NAME}
      MYSQL_USER: ${TRINO_EVENT_DB_USER}
      MYSQL_PASSWORD: ${TRINO_EVENT_DB_PASSWORD}
    volumes:
      - trino-event-db-data:/var/lib/mysql
    networks:
      internal:
        ipv4_address: ${TRINO_EVENT_DB_IP}
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      retries: 5
      timeout: 5s

  trino-coordinator:
    hostname: trino-coordinator
    container_name: trino-coordinator
    build:
      context: ${PWD}/trino
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      # - '9080:9080'
      # - '9081:9081'
      # - '12345:12345'
    volumes:
      - ${PWD}/trino/coordinator/config.properties:/etc/trino/config.properties
      # - ${PWD}/trino/coordinator/jvm.config:/etc/trino/jvm.config
      # - ${PWD}/trino/coordinator/jmx-config.yaml:/etc/trino/jmx/config.yaml
      # - ${PWD}/trino/coordinator/mysql-event-listener.properties:/etc/trino/mysql-event-listener.properties
      - ${PWD}/secrets/gcp-sa.json:/opt/gcp/secrets/service-account.json
      - ${PWD}/trino/catalog/iceberg.properties:/etc/trino/catalog/iceberg.properties
      # - ${PWD}/trino/common/exchange-manager.properties:/etc/trino/exchange-manager.properties
    # restart: always
    depends_on:
      # trino-event-db:
        # condition: service_healthy
      hive-server:
        condition: service_healthy
    networks:
      - internal
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/v1/info']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s

  trino-worker:
    build:
      context: ${PWD}/trino
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/trino/worker/config.properties:/etc/trino/config.properties
      - ${PWD}/secrets/gcp-sa.json:/opt/gcp/secrets/service-account.json
      - ${PWD}/trino/catalog/iceberg.properties:/etc/trino/catalog/iceberg.properties
      # - ${PWD}/trino/common/exchange-manager.properties:/etc/trino/exchange-manager.properties
    depends_on:
      # trino-event-db:
      #   condition: service_healthy
      trino-coordinator:
        condition: service_healthy
    # restart: always
    deploy:
      replicas: 1
    networks:
      - internal

  superser-backend-db:
    container_name: superser-backend-db
    hostname: superser-backend-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${SUPERSET_BACKEND_DB_USER}
      POSTGRES_PASSWORD: ${SUPERSET_BACKEND_DB_PASSWORD}
      POSTGRES_DB: ${SUPERSET_BACKEND_DB_NAME}
    volumes:
      - superser-backend-db-data:/var/lib/postgresql/data
    networks:
      internal:
        ipv4_address: ${SUPERSET_BACKEND_DB_IP}
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${SUPERSET_BACKEND_DB_USER}']
      interval: 10s
      retries: 5
      timeout: 5s

  superset:
    container_name: superset
    hostname: superset
    build:
      context: ${PWD}/superset
      dockerfile: Dockerfile
    depends_on:
      superser-backend-db:
        condition: service_healthy
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
      - SUPERSET_CONFIG_PATH=/app/superset_config.py
    volumes:
      - ${PWD}/superset/superset_config.py:/app/superset_config.py
    ports:
      - '8088:8088'
    networks:
      - www
      - internal

  superset-init:
    container_name: superset-init
    hostname: superset-init
    build:
      context: ${PWD}/superset
      dockerfile: Dockerfile
    command: ' /opt/bin/docker-init.sh'
    depends_on:
      superser-backend-db:
        condition: service_healthy
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
      - SUPERSET_CONFIG_PATH=/app/superset_config.py
    volumes:
      - ${PWD}/superset/superset_config.py:/app/superset_config.py
    networks:
      - internal

volumes:
  trino-event-db-data:
  hive-metastore-db-data:
  superser-backend-db-data:

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: ${INTERNAL_SUBNET}
  www:
