apiVersion: v2
name: helm
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: "1.0.0"
dependencies:
  - name: helm1
    repository: file://charts/helm1
    condition: helm1.enabled
  - name: helm2
    repository: file://charts/helm2
    condition: helm2.enabled
